flights_warehouse:
  target: warehouse
  outputs:
    warehouse:
      type: postgres
      threads: 4
      host: warehouse_db
      port: 5432
      user: airflow
      password: airflow
      dbname: warehouse
      schema: final
